// <auto-generated />
namespace Pathfinder.Data.SqlServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class UserRole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserRole));
        
        string IMigrationMetadata.Id
        {
            get { return "201401060849177_UserRole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
